name: iosApp
options:
  bundleIdPrefix: com.parkwoocheol.sample
targets:
  iosApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: iosApp

    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.parkwoocheol.sample.kmpdatastore
      INFOPLIST_FILE: iosApp/Info.plist
      FRAMEWORK_SEARCH_PATHS:
        - $(inherited)
        - $(PROJECT_DIR)/../shared/build/bin/iosSimulatorArm64/debugFramework
      OTHER_LDFLAGS:
        - $(inherited)
        - -framework
        - Shared
    dependencies:
      - framework: ../shared/build/bin/iosSimulatorArm64/debugFramework/Shared.framework
        embed: true
