name: iosApp
options:
  bundleIdPrefix: com.parkwoocheol.sample
targets:
  iosApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: iosApp
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.parkwoocheol.sample.kmpdatastore
      INFOPLIST_FILE: iosApp/Info.plist
      FRAMEWORK_SEARCH_PATHS: "$(SRCROOT)/../../sample/shared/build/bin/iosSimulatorArm64/debugFramework"
      OTHER_LDFLAGS: "$(inherited) -framework Shared"
    preBuildScripts:
      - name: Build KMP Shared Framework
        script: |
          if [ -f ~/.zshrc ]; then
              source ~/.zshrc
          elif [ -f ~/.bash_profile ]; then
              source ~/.bash_profile
          fi
          
          if [ -z "$JAVA_HOME" ]; then
              export JAVA_HOME=$(/usr/libexec/java_home)
          fi

          cd "$SRCROOT/../../"
          ./gradlew :sample:shared:linkDebugFrameworkIosSimulatorArm64
    dependencies:
       - framework: ../shared/build/bin/iosSimulatorArm64/debugFramework/Shared.framework
         embed: true
